version: "3.9"
services:
  app:
    build:
      context: app
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf:ro
      - ./certyfikat.crt:/etc/nginx/certyfikat.crt
      - ./klucz-priv.key:/etc/nginx/klucz-priv.key
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"